### ISSUE TITLE
Loading tensorflow 1.9 module breaks numpy on python 3.6

### ISSUE THREAD

**Issue by fcalvet** [Svdvoort/Radiomics-GPU-Server#10]
```
module purge
module load compilers/python/3.6.6
module load tensorflow/1.9.0
python3
>>>import numpy as np
```
outputs the following error:
> Traceback (most recent call last):
>   File "/packages/tensorflow/1.9.0/Python-3.5.6/numpy/core/__init__.py", line 16, in <module>
>     from . import multiarray
> ImportError: cannot import name 'multiarray'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/packages/tensorflow/1.9.0/Python-3.5.6/numpy/__init__.py", line 142, in <module>
>     from . import add_newdocs
>   File "/packages/tensorflow/1.9.0/Python-3.5.6/numpy/add_newdocs.py", line 13, in <module>
>     from numpy.lib import add_newdoc
>   File "/packages/tensorflow/1.9.0/Python-3.5.6/numpy/lib/__init__.py", line 8, in <module>
>     from .type_check import *
>   File "/packages/tensorflow/1.9.0/Python-3.5.6/numpy/lib/type_check.py", line 11, in <module>
>     import numpy.core.numeric as _nx
>   File "/packages/tensorflow/1.9.0/Python-3.5.6/numpy/core/__init__.py", line 26, in <module>
>     raise ImportError(msg)
> ImportError: 
> Importing the multiarray numpy extension module failed.  Most
> likely you are trying to import a failed build of numpy.
> If you're working with a numpy git repo, try `git clean -xdf` (removes all
> files not under version control).  Otherwise reinstall numpy.
> 
> Original error was: cannot import name 'multiarray'

If Python 3.5.6 or TensorFlow 1.10.0 is loaded instead, it works

**Comment by Svdvoort** [comment]
There was a bug in the creation of the module file for tensorflow, it is solved in  9487207.
