### ISSUE TITLE
Package virtualenv is missing in python 2

### ISSUE THREAD

**Issue by gsmaria** [Svdvoort/Radiomics-GPU-Server#4]
I have tried to create a virtual environment to run python 2.7.15 but the package virtualenv is not available

**Comment by Svdvoort** [comment]
It should be available in Python 2.7.15, it is not available in Python 2.7.12 because of issue #3

**Comment by Svdvoort** [comment]
This issue is solved since 694efffb84bbe1d2dd1e7885ab99f346be842b7f
