### ISSUE TITLE
matplotlib doesn't work, due to bzip2 missing

### ISSUE THREAD

**Issue by fcalvet** [Svdvoort/Radiomics-GPU-Server#5]
When trying to load matplotlib, the following error occurs:
>   File "/home/fcalvet/clm_seg/basicFunctions.py", line 1, in <module>
>     import matplotlib
>   File "/home/fcalvet/CNN4/lib/python3.6/site-packages/matplotlib/__init__.py", line 127, in <module>
>     from . import cbook
>   File "/home/fcalvet/CNN4/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 13, in <module>
>     import bz2
>   File "/packages/python/3.6.6/lib/python3.6/bz2.py", line 23, in <module>
>     from _bz2 import BZ2Compressor, BZ2Decompressor
> ModuleNotFoundError: No module named '_bz2'

This is probably because bzip2  wasn't available during the python compilation, according to https://stackoverflow.com/questions/8115280/importerror-no-module-named-bz2-for-python-2-7-2#14123902. A quick way to check is `python(3) -c "import bz2; print(bz2.__doc__)"`

However this should be solved by a9ba37f, so may be re-compiling the Pythons is needed

PS: thanks for adding the conflict error when trying to load multiples Python versions

**Comment by Svdvoort** [comment]
You're right, python 3.6.6 was not installed  with these latest versions so
that's the problem. Should be an easy fix by running the install script
again.

**Comment by fcalvet** [comment]
Was fixed by running the install script, closing the issue
