### ISSUE TITLE
install graphviz by default

### ISSUE THREAD

**Issue by fcalvet** [Svdvoort/Radiomics-GPU-Server#7]
Graphviz (https://www.graphviz.org/) is a useful library to make graphs.
It's used as the backend of some tools, such as https://keras.io/visualization/, to visualize the computational graph of neural networks. However python interfaces for it don't include the binaries which must be installed separately with root access (to use apt).

**Comment by Svdvoort** [comment]
Solved with 84de48281740525759ffa1897f665c86c357ffab
